///|
using @core {type ChatTree, type ChatTreeSnapshot, type Message, type Role}

///|
using @qt {
  type NullptrError,
  type Signal,
  type Alignment,
  type QMainWindow,
  type QWidget,
  type QBoxLayout,
  type QScrollArea,
  type QSplitter,
  type QStackedWidget,
  type QToolBar,
  type QSizePolicy,
  type QToolButton,
  type QButtonGroup,
  type QComboBox,
  type QDialog,
  type QDialogButtonBox,
  type QGridLayout,
  type QLineEdit,
  type QPlainTextEdit,
  type QObject,
  type QNetworkAccessManager,
  type QNetworkReply,
  type QNetworkRequest,
  type QTextDocument,
  type QPushButton,
  type QLabel,
  trait AsWidget,
  trait AsObject,
}
